### ISSUE TITLE
Progress bar doesn't align correctly (subtask of issue 106)

### ISSUE THREAD

**Issue by ywkim312** [IN-CORE/incore-playbook#135]
this is a subtask of https://github.com/IN-CORE/incore-playbook/issues/106

**Comment by ywkim312** [comment]
duplicated issue with https://github.com/IN-CORE/incore-playbook/issues/139

**Comment by longshuicy** [comment]
Ah sorry i didn't see you already created a task~

**Comment by ywkim312** [comment]
no worries. closed mine
