### ISSUE TITLE
put the datawolf dataset content (incore ids) to the common space

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-playbook#136]
This issue is related to download execution results. e.g. download epf damage e.g.63ee8028695e0f5726304f68

_Originally posted by @longshuicy in https://github.com/IN-CORE/incore-playbook/issues/106#issuecomment-1433596301_
            

 1. on the frontend we can add logic to put certain dataset content (incore ids) to the common testbed space
 2. on datawolf end, when datawolf posting to incore services, need to put the id to the common space

**Comment by longshuicy** [comment]
Sadly i don't think this is possible to do from frontend:

E.g. dataset id 63ee8047695e0f5726305057 belongs to my personal space cwang138 (because I ran this workflow); another user "commresilience" is not able to put that id into the testbed space even though they have write access. I think it's because they cannot access other people's dataset.

What should we do? Thoughts? @navarroc

**Comment by navarroc** [comment]
Why can't cwang138 run the workflow and then after running the workflow, use cwang138's credentials to add the dataset to the community space?  We don't need the commresilience user to do it. So if cwang138 is using the Joplin app, that user should put the datasets they want to share into the community space.

**Comment by longshuicy** [comment]
> Why can't cwang138 run the workflow and then after running the workflow, use cwang138's credentials to add the dataset to the community space? We don't need the commresilience user to do it. So if cwang138 is using the Joplin app, that user should put the datasets they want to share into the community space.

Ah i see! haha i was thinking too much "in the box"!

**Comment by longshuicy** [comment]
wait... but the user at the time submit the workflow are not guaranteed to wait along while the results are computing hence not guaranteed to have the id yet?

**Comment by navarroc** [comment]
That's a good point. Long running workflows or if the person leaves before the workflow finishes could pose and issue. I think we can handle this all on the workflow side then.

**Comment by longshuicy** [comment]
All the new workflows (galveston, SLC) will use the new tool Chris creates that lets the user specify the space so it's not hard coded like it is for Joplin now.
