### ISSUE TITLE
fix status bar appearance for a smaller screen/ different browser 

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-playbook#139]
Try Safari, it looks like:
<img width="461" alt="image" src="https://user-images.githubusercontent.com/13950475/220153238-e380e480-3a73-44fa-b2d4-1c18abd9d3fe.png">

But it should looks like this:
![image](https://user-images.githubusercontent.com/13950475/220152789-9eda6c1c-3f61-4d69-a0e8-cebcaffba06a.png)

**Comment by ywkim312** [comment]
I made a issue https://github.com/IN-CORE/incore-playbook/issues/135 but this looks better. I will close mine :)
