### ISSUE TITLE
pagination of datawolf execution

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-playbook#151]

**Comment by longshuicy** [comment]
Does datawolf supports pagination?

**Comment by navarroc** [comment]
> Does datawolf supports pagination?

Yes, you can pass in a page, size and userid.to executions endpoint and it will return a subset of values based on what's passed. I can give an example later.

**Comment by navarroc** [comment]
Here's an example to fetch 2 executions per page:

https://incore-dev.ncsa.illinois.edu/datawolf/executions?email=cnavarro&page=0&size=2
https://incore-dev.ncsa.illinois.edu/datawolf/executions?email=cnavarro&page=1&size=2

**Comment by longshuicy** [comment]
> Here's an example to fetch 2 executions per page:
> 
> https://incore-dev.ncsa.illinois.edu/datawolf/executions?email=cnavarro&page=0&size=2 https://incore-dev.ncsa.illinois.edu/datawolf/executions?email=cnavarro&page=1&size=2

Do we know how many pages in total?

**Comment by navarroc** [comment]
> > Here's an example to fetch 2 executions per page:
> > https://incore-dev.ncsa.illinois.edu/datawolf/executions?email=cnavarro&page=0&size=2 https://incore-dev.ncsa.illinois.edu/datawolf/executions?email=cnavarro&page=1&size=2
> 
> Do we know how many pages in total?

No :(  

Also, that fetches in ascending order. I sense a future improvement to Datawolf, but in the meantime, you can get them in descending order by changing the API call to:

https://incore-dev.ncsa.illinois.edu/datawolf/workflows/[workflow-id]/executions?email=user-id&page=0&size=2

**Comment by longshuicy** [comment]
> > > Here's an example to fetch 2 executions per page:
> > > https://incore-dev.ncsa.illinois.edu/datawolf/executions?email=cnavarro&page=0&size=2 https://incore-dev.ncsa.illinois.edu/datawolf/executions?email=cnavarro&page=1&size=2
> > 
> > 
> > Do we know how many pages in total?
> 
> No :(
> 
> Also, that fetches in ascending order. I sense a future improvement to Datawolf, but in the meantime, you can get them in descending order by changing the API call to:
> 
> [https://incore-dev.ncsa.illinois.edu/datawolf/workflows/[workflow-id]/executions?email=user-id&page=0&size=2](https://incore-dev.ncsa.illinois.edu/datawolf/workflows/%5Bworkflow-id%5D/executions?email=user-id&page=0&size=2)

haha oops im creating more works...

I dont worry about the ordering because there is logic on the frontend to sort the execution by any field (creator, date, etc...) and it's default to be the depending order of date.
