### ISSUE TITLE
migrate geoserver styles to prod

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-playbook#156]
The layer style we are using on dev are

- [x] incore:earthquake-pga-g
- [x] incore:tornado
- [x] incore:hurricane-wind
- [x] incore:joplin-substations-label
- [x] incore:bldg-dmg-summary
- [x] incore:joplin-bldg-func
- [x] incore:epf-dmg-summary
- [x] incore:bldg-dmg-summary
- [x] incore:heatmap
- [x] incore:epf-dmg-summary

**Comment by ywkim312** [comment]
@longshuicy can you point out what layers should be migrated?

**Comment by longshuicy** [comment]
Sorry not layer, just the style need to be migrated

**Comment by ywkim312** [comment]
oops my bad, not the layer, style. Let me know what styles should be migrated.

**Comment by longshuicy** [comment]
> oops my bad, not the layer, style. Let me know what styles should be migrated.

I put those in the description ^. Thanks!

**Comment by ywkim312** [comment]
thank you! 👍

**Comment by ywkim312** [comment]
done
