### ISSUE TITLE
big image on login page shows up below the login div for all 3 apps

### ISSUE THREAD

**Issue by jonglee1** [IN-CORE/incore-playbook#253]
big image on login page shows up below the login div3 apps.
After refresh the page, it locates on the right place.

![image](https://user-images.githubusercontent.com/5861374/230194093-d3ab89c3-db64-4ce1-a1d9-564fd8785920.png)

**Comment by Rashmil-1999** [comment]
I loaded the page and it looks fine. Could it be a one-time thing? does it happen on every fresh load?
