### ISSUE TITLE
Improve/fix pop dislocation heatmap

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-playbook#279]
Need to remove population dislocation heatmap and replace it by showing the dislocation layer
Need to figure out how to color it.

---

TODOs:
~~- Need to test save the pyincore-viz generated heatmap into raster/shapefile~~
- need to write pyincore-viz method to plot static heatmap (not using ipyleaflet) and save into a format (shp/raster/geopackage whichever is the most suitable)...
- and post to geoserver to generate the layer
- render on the browser 
- create/test proper geoserver styling 
- remove damage layer and show heatmap only, so we can click on heatmap

Maybe write a short notebook for the creating and posting layer part?

**Comment by longshuicy** [comment]
@jonglee1 will check with Sara to see if heatmap is still needed if we display detail properties of each building (e.g. allocated or not; number of people who allocated)

**Comment by longshuicy** [comment]
No need to show heatmap. Closing the issue.

**Comment by ylyangtw** [comment]
numprec

**Comment by ylyangtw** [comment]
incore:heatmap
