### ISSUE TITLE
Displaying the value of the map features (damages and building attributes)

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-playbook#284]
@Rashmil-1999 
Follow up things need to be done:
1. Move clicking event to the Map component; always assume the first layer is the layer (damage, functionality, dislocation layer) we read properties
2. Add a flag as props to turn on/off property selection clicking
3. Upon design ready:

```[tasklist]
### Tasks
  - [ ] https://github.com/IN-CORE/incore-playbook/issues/303
  - [ ] https://github.com/IN-CORE/incore-playbook/issues/304
```

-----

When clicking a building on map show the feature of the building such as damage, building attributes etc. It is needed especially when user compare two different scenarios. 

Technologies to consider:
- Query Geoserver WMS to return properties (which might be slow)
In order to display the property (attribute) of the building, we can use "WMS GetFeatureInfo" which supported by OpenLayers. Here is an example: https://openlayers.org/en/latest/examples/getfeatureinfo-layers.html
[9:22](https://ncsa-at-illinois.slack.com/archives/G9BH2ETSM/p1708010553157309)
another example: https://openlayers.org/en/latest/examples/getfeatureinfo-tile.html

~~Geojson (browser might not be able to handle all building in SLC using geojson). Need to rewrite openlayer part to work with geojson~~
~~vector tile (more performant version of geojson)~~

**Comment by Rashmil-1999** [comment]
The top most layer is *not* to be selected always as the damage layer as the order followed is [basemaps, hazards, [damage, other damage]] so it could be always 3rd. However, since its in a group with name Damage, I look for it. So, moving forward it is imperative to set building damage layer group's name as `Damage`.
