### ISSUE TITLE
Map style for retrofit strategies

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-playbook#344]
Here are the 20 colors

1. "#C32541", 
2. "#1B3EBB",
3. "#76930F",
4. "#268FB0",
5. "#BB772B",
6. "#F54362",
7. "#456AEA",
8. "#98BB1D",
9. "#47B4D6",
10. "#E29D50",
11. "#FC7F95",
12. "#7C95EC",
13. "#C9DF7A",
14. "#83DEF2",
15. "#F4C189",
16. "#FDBBC9",
17. "#DBD2FC",
18. "#E0E9C2",
19. "#CDECF0",
20. "#FFE3C4",

Here is a layer you can use: `incore:65f87717e42f3b0da55e47fe` (dev)

**Comment by jonglee1** [comment]
Style is created on both Dev and Prod
Name of the style **incore:retrofit-rules**

![image](https://github.com/IN-CORE/incore-playbook/assets/5861374/f892eb60-1366-4c87-b4ac-ab26bdeccddb)
