### ISSUE TITLE
Damage comparison table alignment bug

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-playbook#358]
The last column for some reason is not aligning with the rest. E.g. the "accept" column

<img width="443" alt="DESTROYED" src="https://github.com/IN-CORE/incore-playbook/assets/13950475/d8d50680-3046-4cdd-8918-f6ea025dcd27">

**Comment by ylyangtw** [comment]
fixed in https://github.com/IN-CORE/incore-playbook/pull/379
