### ISSUE TITLE
Population dislocation layer map style

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-playbook#361]
incore:galveston-pop-dis
incore:slc-pop-dis
incore:joplin-pop-dis

Need to update frontend map config to match these 3 styles

---

if no disolocation -> 0 value
if yes dislocation -> numprec value

colors to use:
#D14936
#FD9B64
#F2DC8C
#8AD87D
#666666

---
Galveston 
layer id: 65f1c863e0de8c5c3288b3ff (dev)
possible numprec range: 0 - 1002

SLC 
layer id: 65eb94054331420c85e3ba6d (dev)
possible numprec range: 0-2503 

Joplin 
layer id: 6422064db18d026e7c8011a7 (dev)
possible numprec range:  0 - 578 (578 only has 1 case)

-----

Categorize? Interpolate?
https://docs.geoserver.org/stable/en/user/styling/sld/tipstricks/transformation-func.html

This layer only contains dislocated buldings' numprec (Number of occupants in a living unit).

Details see:
https://github.com/navarroc/pyincore-datawolf/blob/main/pop_dislocation_post_process.py
and 
https://github.com/IN-CORE/pyincore/blob/develop/pyincore/utils/popdisloutputprocess.py#L78

![Image](https://github.com/IN-CORE/incore-playbook/assets/13950475/452fdac2-aa4b-4205-82cb-b7f5821aec9c)

----

Need some discussion

1. Research on the population dislocation layer step --> we seem to create a shapefile and post that to the dataservice/geoserver
2. Numprec what does that mean
3. run population dislocation --> get the complete output and identify which fields can be used
4. Need to come up with the style

**Comment by jonglee1** [comment]
3 styles are created and published on both incore-dev and incore-prod Geoserver
- incore:galveston-pop-dis
- incore:joplin-pop-dis
- incore:slc-pop-dis
