### ISSUE TITLE
Repoulate the SLC cost table

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-playbook#389]
New data provided by Omar S filling in all missing costs. Need to repopulate the `slc_bldg_ret_cost`

Tabel: https://github.com/IN-CORE/dev-scripts/pull/48/files#diff-9f87188abc0ca2b6c6a379347eabd4a4ceaffdc3568e81b05af40988cd1ba5e0R7

Script to load csv to table: https://github.com/IN-CORE/dev-scripts/pull/48/files#diff-81e272aee507e416bf30cba8af8953b351c33f362bc2fd6ec9e328c2b80212c3R16

CSV see here https://uofi.app.box.com/file/1474073740178

**Comment by jonglee1** [comment]
The CSV file is created and stored at box share (NIST-Core\Community app\SLC\data_for_RS). The filename is "slc_bldg_retrofit_cost2.csv"

**Comment by jonglee1** [comment]
I will create new task at dev-script repo regarding loading the data to rs_data.db. 
New task: https://github.com/IN-CORE/dev-scripts/issues/50
