### ISSUE TITLE
Missing tornado geoserver style on map

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-playbook#414]
To reproduce it locally, 
1. incore-playbook repo
2. remove `map.config.js`, `global.config.js`
3. copy `map.config.joplin.js` to be `map.config.js`
4. copy `global.config.joplin.js` to be `global.config.js`
5. `npm run start:dev`

the tornado style should be in MapUtil in the `map.config.js`
```
MapUtil: {
		earthquake: "incore:earthquake-pga-g",
		tornado: "incore:tornado",
		hurricane: {
```
---

Our old tornado seems to look like this if you need a reference

![Image](https://github.com/IN-CORE/incore-playbook/assets/13950475/57b2974d-5d91-4c8a-bd0a-31b76ffc5a98)

---
For some reason, we used to have "colorful" tornado styles on dev/prod. But now there is only default "incore:tornado" which just gray. I checked both dev/prod.

e.g. 
https://incore-dev.ncsa.illinois.edu/geoserver/web/wicket/bookmarkable/org.geoserver.wms.web.data.StyleEditPage?9&name=tornado&workspace=incore

**Comment by ywkim312** [comment]
@longshuicy The style in the geoserver looks good. Is community app correctly matching the style to dataset?

**Comment by ywkim312** [comment]
@longshuicy Please check this link https://incore-dev.ncsa.illinois.edu/geoserver/incore/wms?service=WMS&version=1.1.0&request=GetMap&layers=incore%3A64df9a44e55b192654eb2dbf&bbox=-97.51133063798986%2C35.21457835945468%2C-97.43666936201015%2C35.24942164054533&width=768&height=358&srs=EPSG%3A4326&styles=&format=application/openlayers

I manually applied incore:tornado style to the dataset id "64df9a44e55b192654eb2dbf" in dev, and it shows the correct color

**Comment by longshuicy** [comment]
Whenever you have a chance, could you check incore-dev joplin app then? 
https://incore-dev.ncsa.illinois.edu/playbook/joplin/goal-objective-hazard

<img width="1332" alt="image" src="https://github.com/IN-CORE/incore-playbook/assets/13950475/c404c84f-3953-411f-9c7f-fa8ad8a08d36">

**Comment by ywkim312** [comment]
I found a hazard dataset and associate the dataset with the style and it looked okay. 
![image](https://github.com/IN-CORE/incore-playbook/assets/12547573/95b57940-2fb2-4cb2-a395-1ffcbea5306d)
However, this is because I manually worked on it. I don't know how the playbook associate the style to dataset so we might need to check it?
