### ISSUE TITLE
RS builder bugs

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-playbook#435]
1. When building, we should hide/disable previous button. Clicking this button cause a lot of problem
<img width="1399" alt="image" src="https://github.com/IN-CORE/incore-playbook/assets/13950475/351672d2-8290-4ece-bf9a-9a05f0b41599">

2. After creating and close the widget, and try again, sometimes it skip the "step 1" fill name part.

**Comment by Vismayak** [comment]
@longshuicy When you say after creating, do you mean before the output (Review Retrofit Summary) is shown or after?

**Comment by longshuicy** [comment]
> @longshuicy When you say after creating, do you mean before the output (Review Retrofit Summary) is shown or after?

before. When you on that exact screenshot (click the build, but results are in loading).
