### ISSUE TITLE
Update Joplin RS builder labels

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-playbook#450]
Building archetypes:
- 1-story wood-frame residential buildings
- 2-story wood-frame residential buildings  

Retrofit methods:
- Joplin buildings constructed following the 2006 IRC 
- Joplin buildings with a cost-effective retrofit plan 
- Joplin buildings with a high-performance retrofit plan

Make sure to also change Joplin playbook repo as well as the most important part the helm chart "playbook-configs". Thanks!

**Comment by Vismayak** [comment]
Just to clarify, the retrofit methods are to be renamed  and the order is same right 

![Image](https://github.com/IN-CORE/incore-playbook/assets/16596733/41585aa3-59d2-4b52-bc0d-cfe0f461cdcb)

**Comment by Vismayak** [comment]
Once the PRs are approved, I will change the IN-CORE helm files as well @longshuicy
