### ISSUE TITLE
Tweak the format of total cost to be more readable

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-playbook#451]
Per request, we want to change the format of total cost to be more readable. Something e.g 1 Billion 2 Million xxx?
Need to research a bit what available financial format available.

**Comment by Rashmil-1999** [comment]
damn, what a silly request!... let me see what I can do. Just to clarify, $ 790,378,105.06 this should be formatted like, Seven Hundred and Ninty Million Three Hundred and Seventy Eight Thousand One Hundred and Five Dollars and Six Cents ? or what is the format we looking at?
