### ISSUE TITLE
Check certain styles

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-playbook#465]
incore:bldg-dmg-summary. --> 660d985f099327393f8393cc in prod for example 
incore:epf-dmg-summary --> 660d984bdd4ae6390a8f53b9 in prod

These 2 styles are not showing correctly.

**Comment by ywkim312** [comment]
@longshuicy Those have been updated. Please check it out and close this issue if it works okay.

**Comment by longshuicy** [comment]
I'm so sorry that I have missed one; I think galveston it's using `incore:galveston-bldg-dmg-fema`

**Comment by ywkim312** [comment]
> I'm so sorry that I have missed one; I think galveston it's using `incore:galveston-bldg-dmg-fema`

Those has been updated

**Comment by longshuicy** [comment]
> > I'm so sorry that I have missed one; I think galveston it's using `incore:galveston-bldg-dmg-fema`
> 
> Those has been updated

Works well. Thank you!
