### ISSUE TITLE
Remove LDAP dependency

### ISSUE THREAD

**Issue by Rashmil-1999** [IN-CORE/incore-playbook#480]
We need to replace the forgot password and user registration process through keycloak. Currently it does this through LDAP because while the users can be authenticated via Keycloak, we can't update passwords and because of that we also kept user registration to LDAP. We will need to use keycloak links to handle redirect to register and forget password through keycloak.

Forget password URL pattern: {hostname}/realms/In-core/login-actions/reset-credentials?client_id=react-auth
User registration URL pattern: {hostname}/realms/In-core/login-actions/registration?client_id=react-auth

Note that in Keycloak v17 we need {hostname}/auth/* pattern but with keycloak v24 we no longer need auth/

**Comment by longshuicy** [comment]
This is addressed.
