### ISSUE TITLE
Reconfigure Joplin workflow

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-playbook#75]
Joplin workflow doesn't have multiple steps (Just one big steps)?
Need to check if the latest pyincore was used because some of the execution results have NaN

**Comment by navarroc** [comment]
Done. Updated workflow with multiple steps is created and on dev.

**Comment by longshuicy** [comment]
Need to update with HHRS

**Comment by longshuicy** [comment]
And the kubernetes datawolf

**Comment by longshuicy** [comment]
done. https://incore-dev.ncsa.illinois.edu/datawolf/workflows/05e5ac18-c202-4a8b-973d-01afcae20b14
